FROM postgres:15
# RUN export HTTP_PROXY=http://{username}:{password}@{url} && export HTTPS_PROXY=https://{username}:{password}@{url}
RUN apt-get update && apt-get install -y postgresql-15-postgis-3
CMD ["/usr/local/bin/docker-entrypoint.sh","postgres"]
